### ISSUE TITLE
Wrong AutoScrolling

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#15]
I saw that `document.getElementById('lyrics').scrollIntoView()` is used in the script.

However, if `iframe.contentWindow.postMessage({ iAm: custom.scriptName, type: 'scrollLyrics', position: positionFraction }, '*')` is called, the `positionFraction` from `0.0` to `1.0` is not referred to the location of `#lyrics` (it seems refer to the scrollHeight of the entire iframe)

**Comment by cyfung1031** [comment]
I have checked the coding and found that the implementation is not bad. Just changed dom removal to dom visibility change (collaspe vs hidden) to avoid reflow.

This issue is now closed.

**Comment by cvzi** [comment]
I think it should only do `document.getElementById('lyrics').scrollIntoView()` if auto scrolling is disabled and if auto scrolling is enabled, it could do `theme.scrollLyrics(0)` to go to the scroll position of 0 seconds.

**Comment by cyfung1031** [comment]
> I think it should only do `document.getElementById('lyrics').scrollIntoView()` if auto scrolling is disabled and if auto scrolling is enabled, it could do `theme.scrollLyrics(0)` to go to the scroll position of 0 seconds.

I am not sure is it due to *Genius React with Primis* or not. My `#lyrics` is nothing (zero height). I thought it is intended for scrollview's pseudo element. I changed it to `LyricsWrapper` which is the container of both `#lyrics` and lyrics contents.

<img width="750" alt="Screen Shot 2022-12-21 at 20 24 43" src="https://user-images.githubusercontent.com/44498510/208894922-331d23c2-018f-4e5a-97af-609b82495e63.png">

Now I understand the code and now I explain to you what I did recently regarding the autoscroll.
I suggest you should also review like the offset position.

At the beginning, I do not recognize the negative offset which is the default beginning position. 
I think you would like to delay it because the first line is at the top.
I am thinking another way that, just make the content length longer.

`position = 0.0` shall be showing the first line in the middle
`position = 1.0` shall be showing the last line in the middle.
So iframe height is `100vh`, add `50vh` as `padding-top` and `50vh` as `padding-bottom`.

Now the calculation would be much simpler - 0.0 ~ 1.0 is fully corresponding to the content `scrollHeight`
In such design, delaying (negative offset) shall be not required, but I still make some and looks great. (reduce 200 to 120)

However I only changed the Genius React theme for this delaying.
I do some magic CSS to make the information headers to occupy the upper space of the lyrics (`max-height: 50vh`)
I just noticed that it only works in *Genius React with Primis*... sigh.

Really need to review the styling issues... looks like autoscrolling is not working for the normal Genius React as well...

**Comment by cvzi** [comment]
> looks like autoscrolling is not working for the normal Genius React as well...

I think because of this event. The animation is attached to a "Primis" selector
https://github.com/cvzi/genius-lyrics-userscript/pull/37/files#diff-de851c94e95886352209196ce739771f26028847983945cd3059fc931025fca4L1179-R1182
