### ISSUE TITLE
What is the purpose of these codes?

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#16]
```

  function freshWindowFromIframe () {
    const iframe = document.body.appendChild(document.createElement('iframe'))
    iframe.style.display = 'none'
    return iframe.contentWindow
  }
  const setTimeout = function (a, b) {
    if (window.setTimeout.toString().indexOf('[native code]') !== -1) {
      return window.setTimeout(a, b)
    }
    if (top.setTimeout.toString().indexOf('[native code]') !== -1) {
      return top.setTimeout(a, b)
    }
    if (!cleanWindow && document.body) {
      cleanWindow = freshWindowFromIframe()
    }
    if (cleanWindow) {
      return cleanWindow.setTimeout(a, b)
    } else {
      return window.setTimeout(a, b)
    }
  }
  const setInterval = function (a, b) {
    if (window.setInterval.toString().indexOf('[native code]') !== -1) {
      return window.setInterval(a, b)
    }
    if (top.setInterval.toString().indexOf('[native code]') !== -1) {
      return top.setInterval(a, b)
    }
    if (!cleanWindow && document.body) {
      cleanWindow = freshWindowFromIframe()
    }
    if (cleanWindow) {
      return cleanWindow.setInterval(a, b)
    } else {
      return window.setInterval(a, b)
    }
  }
  const clearTimeout = function (a, b) {
    if (window.clearTimeout.toString().indexOf('[native code]') !== -1) {
      return window.clearTimeout(a, b)
    }
    if (top.clearTimeout.toString().indexOf('[native code]') !== -1) {
      return top.clearTimeout(a, b)
    }
    if (!cleanWindow && document.body) {
      cleanWindow = freshWindowFromIframe()
    }
    if (cleanWindow) {
      return cleanWindow.clearTimeout(a, b)
    } else {
      return window.clearTimeout(a, b)
    }
  }
  const clearInterval = function (a, b) {
    if (window.clearInterval.toString().indexOf('[native code]') !== -1) {
      return window.clearInterval(a, b)
    }
    if (top.clearInterval.toString().indexOf('[native code]') !== -1) {
      return top.clearInterval(a, b)
    }
    if (!cleanWindow && document.body) {
      cleanWindow = freshWindowFromIframe()
    }
    if (cleanWindow) {
      return cleanWindow.clearInterval(a, b)
    } else {
      return window.clearInterval(a, b)
    }
  }
```

I cannot notify any declaration of `setTimeout`, `setInterval`, `clearTimeout`, and `clearInterval` in the script. What is the purpose of these coding?

**Comment by cvzi** [comment]
It is necessary on Spotify, because the Spotify page overwrites `setTimeout` and the other functions. This is a way to get the built-in functions back. I don't know if there is a simpler way to do it, but this works.

**Comment by cyfung1031** [comment]
> It is necessary on Spotify, because the Spotify page overwrites `setTimeout` and the other functions. This is a way to get the built-in functions back. I don't know if there is a simpler way to do it, but this works.

Understand, but why you cannot use the modified setTimeout? I checked that its implementation is the same as the native. Perhaps Spotify just want to do some logging.

**Comment by cvzi** [comment]
I have not checked it since I added that. Maybe it has changed. At the time, their implementation was really slow, because it send and waited for a request to the Spotify server before running.

**Comment by cyfung1031** [comment]
> I have not checked it since I added that. Maybe it has changed. At the time, their implementation was really slow, because it send and waited for a request to the Spotify server before running.

I have figure out that Spotify use two different implementations of setTimeout.

First is a fake window object and fake setTimeout / setInterval.

<img width="336" alt="Screen Shot 2022-12-15 at 21 58 36" src="https://user-images.githubusercontent.com/44498510/207865281-a6378858-f90e-443f-b15e-8455c7aeba74.png">


Second one can work as normal although it is modified.

<img width="813" alt="Screen Shot 2022-12-15 at 21 59 06" src="https://user-images.githubusercontent.com/44498510/207865301-c8085e3a-22e9-415c-8d6b-1c61d8a78354.png">
