### ISSUE TITLE
whether the songTitle should change if beLessSpecific is false?

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#26]
<img width="844" alt="Screen Shot 2022-12-16 at 20 58 39" src="https://user-images.githubusercontent.com/44498510/208093519-aca3d847-df0a-4346-9387-0b9637f348ae.png">

The line `const simpleTitle = songTitle = songTitle.replace(/\s*-\s*.+?$/, '')` shall be `const simpleTitle = songTitle.replace(/\s*-\s*.+?$/, '')` instead?

**Comment by cvzi** [comment]
yes you are right
