### ISSUE TITLE
Option to prefer the "romanized" version of the lyrics when listening to Japanese songs

### ISSUE THREAD

**Issue by cvzi** [cvzi/genius-lyrics-userscript#49]
Ref: https://greasyfork.org/en/scripts/386259-youtube-genius-lyrics/discussions/180050

**Comment by cyfung1031** [comment]
Yes. it can. Please add an option to that option menu to change the preference by the user first.

Then use it to modify the score inside the calculation of score.

I am busy for these days and cannot really code this sorry...

**Comment by cyfung1031** [comment]
Remarks:

In YouTube Genius Lyrics, there is one more thing coded there to match the default lyrics.
In genius lyrics, score is calculated. It is the same no matter the website player you are using.

> (Step 1: ) Webpage Information -> extracted to minimum -> do a search to get hit results as much as possible

This is true for all website player.

However, in YouTube, the results might be not desired as the information provided for searching is too conceptual. the script will try to ask the results even it is just a music (which is not known before searching hits)

After getting the result, YouTube Genius Lyrics will check all those results matching the page information or not.

> (Step 2: ) hit results -> match page info? -> filter -> display -> (might select the first one as default)

But as I remember, the checking shall be not affected by whether it is romaji or not. That is another mechanism to check.

Just a remark here in case the change in score calculation would not work as expected.

**Comment by cyfung1031** [comment]
Are you going to add the option in the option menu?

**Comment by cvzi** [comment]
I don't have much time at the moment. I don't know when I can do it. 

If you want to add it, go ahead.
