### ISSUE TITLE
`Reflect` might be not required

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#52]
https://github.com/cvzi/genius-lyrics-userscript/blob/c20cedd3d18802c1e4a9d239e66f21518e18c844/GeniusLyrics.js#L4284

GPT Answer 1
<img width="535" alt="Screen Shot 2023-05-04 at 19 14 45" src="https://user-images.githubusercontent.com/44498510/236176360-0362f21f-8381-43ab-98aa-1f4457a43a45.png">

GPT Answer 2
<img width="534" alt="Screen Shot 2023-05-04 at 19 17 11" src="https://user-images.githubusercontent.com/44498510/236176826-60209f23-d768-4973-98f7-b58429d856f6.png">

**Comment by cvzi** [comment]
I think it's better to just hard-code the value. That's clearer and it's not a good idea to rely on the order of the keys of an object.
