### ISSUE TITLE
Question about type of script

### ISSUE THREAD

**Issue by Martii** [cvzi/genius-lyrics-userscript#6]
I've noticed that you put this script as a library script on OUJS. i.e. the `// ==UserLibrary==` metadata block and of course the .js only extension.

If you have a specific reason why you are using `@grant` in it I'd like to know please.

Eventually this script is not going to be served... so it is important to understand your reasoning.

Thanks for the look,
OUJS Admin

**Comment by cvzi** [comment]
This used to be a userscript but it turned into a library script. I left the `@grant` in there to remember that I have to copy them to any script that uses this library script.
I can remove or corrupt the `@grant` it they are not allowed on OUJS in library scripts

**Comment by Martii** [comment]
Okay... well for all the bad actors that are hitting OUJS they are already input restricted. Just wanted to make sure I wasn't missing something. Thanks for your input.

One more question... since you use `@connect` that is also on our targeting range soon. Do you see any issues with that? i.e. Is that also a "reminder" that could be put outside of the blocks?

**Comment by cvzi** [comment]
Yes same for `@connect`, not other purpose than to remind myself.
I have removed the `@grant`, `@connect` from this one and from my other library scripts and also a `@require`

**Comment by Martii** [comment]
Appreciate your time and feedback. :smile_cat:

**Comment by Martii** [comment]
@cvzi 

Btw... I'm sponsoring you for Moderator-ship on OUJS. You've consistently proven yourself more importantly to the community and of course impressed me over the years. 

Doesn't mean you have more work. ;) Just means more privileges *(when they get written)*.

Hope to see you there a bit in your spare time.

OUJS Admin.

**Comment by cvzi** [comment]
@Martii Thank you for your confidence, I will try to help out :)
