### ISSUE TITLE
Options not saved in YouTube Music and YouTube

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#69]
Options are always the default values. Refresh the pages and the values will reset to default.
Both checker boxes and select boxes.

I have disabled all other extensions and userscripts.

This issue only happens in YouTube Music Genius Lyrics & YouTube Genius Lyrics.
Not happen in Spotify Genius Lyrics.

@cvzi is it due to the recent updates?

**Comment by cvzi** [comment]
It still works for me on both Youtube and Youtube Music in Chrome and Firefox.

**Comment by cyfung1031** [comment]
Confirmed due to a bug in latest build of Violentmonkey https://github.com/violentmonkey/violentmonkey/issues/1915.
