### ISSUE TITLE
Oops! Sorry, could not transform the genius page

### ISSUE THREAD

**Issue by Demaar** [cvzi/genius-lyrics-userscript#83]
themeName:  Spotify
Error:      Neither "Lyrics__Container" nor "LyricsPlaceholder__Container" found
URL:        https://www.youtube.com/watch?v=HIk73rPZsrQ&list=RDGMEMHDXYb1_DDSgDsobPsOFxpA&index=7
Genius:     https://genius.com/Demondice-appasayo-lyrics
Song:       Appasayo by DEMONDICE
Browser:    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by cvzi** [comment]
It should work again now

**Comment by Demaar** [comment]
It does. Do I create a new issue for each of the others I find? Because I did.
themeName:  Spotify
Error:      Neither "Lyrics__Container" nor "LyricsPlaceholder__Container" found
URL:        https://www.youtube.com/watch?v=a6fMTu-0NoU&list=RDMM&index=17
Genius:     https://genius.com/Anime-allstars-wir-drehen-auf-digimon-02-lyrics
Song:       Wir drehen auf (Digimon 02) by Anime Allstars (Ft. Fred Röttcher)
Browser:    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by cvzi** [comment]
Can you go in the Options of the script and click to clear the cache. And then reload (F5) the page. Maybe that helps. I forgot to add to the update that it automatically clears the cache.

**Comment by Demaar** [comment]
Yeah, seemed like that was the issue. Thanks.
