### ISSUE TITLE
😱 Oops!

### ISSUE THREAD

**Issue by Argetzz** [cvzi/genius-lyrics-userscript#84]
😱 Oops!

Sorry, could not transform the genius page
The lyrics cannot be shown with the theme "Spotify" (yet)
Could you inform the author of this program about the problem and provide the following information:

themeName:  Spotify
Error:      Neither "Lyrics__Container" nor "LyricsPlaceholder__Container" found
URL:        https://open.spotify.com/intl-de/artist/6qIHycJGyzIFBCXc0kg9cM
Genius:     https://genius.com/Pobel-mc-bock-auf-crime-lyrics
Song:       Bock auf Crime by Pöbel MC
Browser:    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0

You can simply post the information on github:
https://github.com/cvzi/genius-lyrics-userscript/issues/
or via email: [cuzi@openmail.cc](mailto:cuzi@openmail.cc)

Thanks for your help!

**Comment by cvzi** [comment]
It should work again now.

**Comment by Argetzz** [comment]
Thank you VERY much for your work <3
